'use client'

import Link from 'next/link'
import { Search, Video, Sparkles, Users, SlidersHorizontal, ArrowUpRight } from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { collection, getDocs, limit, orderBy, query } from 'firebase/firestore'
import { auth, db, onAuthStateChanged, getCurrentCreator } from '../../lib/auth'

type DiscoverVideo = { id:string; creatorId?:string; creatorName?:string; title?:string; description?:string; niche?:string; contentType?:string; youtubeUrl?:string; createdAt?:any }
const niches=['All','Finance','Gospel / Christian','Gaming','Technology','Education','Business','Motivation','Lifestyle','Fitness','Beauty','Comedy','African Creators','Other']

export default function Discover(){
 const router=useRouter(); const [videos,setVideos]=useState<DiscoverVideo[]>([]); const [profile,setProfile]=useState<any>(null); const [search,setSearch]=useState(''); const [niche,setNiche]=useState('All'); const [type,setType]=useState('All'); const [sort,setSort]=useState('match'); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
 useEffect(()=>{const unsub=onAuthStateChanged(auth,async u=>{if(!u){router.replace('/login');return}try{const p=await getCurrentCreator(u.uid);setProfile(p);const snap=await getDocs(query(collection(db,'videos'),orderBy('createdAt','desc'),limit(60)));setVideos(snap.docs.map(d=>({id:d.id,...d.data()} as DiscoverVideo)).filter(v=>v.creatorId!==u.uid))}catch{setError('Could not load creator discovery right now.')}finally{setLoading(false)}});return()=>unsub()},[router])
 const filtered=useMemo(()=>{const q=search.trim().toLowerCase(); const scored=videos.filter(v=>(niche==='All'||v.niche===niche)&&(type==='All'||v.contentType===type)&&(!q||`${v.title||''} ${v.creatorName||''} ${v.niche||''} ${v.description||''}`.toLowerCase().includes(q))).map(v=>{const nicheMatch=profile?.primaryNiche&&v.niche===profile.primaryNiche;const typeMatch=profile?.contentFormat&&profile.contentFormat!=='both'&&v.contentType?.toLowerCase()===profile.contentFormat?.toLowerCase();return {...v,matchScore:(nicheMatch?2:0)+(typeMatch?1:0)}});return scored.sort((a,b)=>sort==='match'?b.matchScore-a.matchScore:sort==='old'?String(a.createdAt||'').localeCompare(String(b.createdAt||'')):String(b.createdAt||'').localeCompare(String(a.createdAt||'')))},[videos,niche,type,search,sort,profile])
 return <main className="appShell"><aside><Link className="brand sideBrand" href="/">theophos<span>hub</span></Link><div className="sideNav"><Link className="sideLink" href="/dashboard">Overview</Link><Link className="sideLink active" href="/discover"><Search size={17}/> Discover</Link><Link className="sideLink" href="/submit"><Video size={17}/> Submit video</Link></div><div className="sideBottom"><Link href="/dashboard">Back to dashboard</Link></div></aside><section className="dash"><header className="dashHead"><div><span className="eyebrow">CREATOR DISCOVERY</span><h1>Find creators worth discovering.</h1><p>We surface content using your niche and interests first, so discovery feels relevant instead of random.</p></div></header><div className="panel" style={{marginBottom:20}}><div style={{display:'flex',gap:12,flexWrap:'wrap',alignItems:'center'}}><input aria-label="Search creators" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search videos, creators or niches..." style={{flex:1,minWidth:220}}/><select aria-label="Content type" value={type} onChange={e=>setType(e.target.value)}><option>All</option><option>Short</option><option>Long-form</option><option>Live</option><option>Other</option></select><select aria-label="Sort" value={sort} onChange={e=>setSort(e.target.value)}><option value="match">Best match</option><option value="new">Newest</option><option value="old">Oldest</option></select></div><div style={{display:'flex',gap:8,flexWrap:'wrap',marginTop:14}}>{niches.map(n=><button key={n} className={niche===n?'choice selected':'choice'} onClick={()=>setNiche(n)}>{n}</button>)}</div></div>{profile?.primaryNiche&&<div className="panel" style={{marginBottom:20}}><div className="panelHead"><div><h3><SlidersHorizontal size={17}/> Personalized discovery</h3><p>Your profile niche is <b>{profile.primaryNiche}</b>. Matching creators are surfaced first.</p></div><span className="choice selected">{filtered.length} results</span></div></div>}{loading?<div className="panel"><p>Loading creators...</p></div>:error?<div className="panel"><p>{error}</p></div>:filtered.length===0?<div className="panel emptyState"><Sparkles size={26}/><b>No matching videos yet.</b><p>Try another niche or search, or be one of the first creators to submit content.</p><Link href="/submit" className="btn primary">Submit your video</Link></div>:<div className="dashGrid">{filtered.map(v=><article className="panel" key={v.id}><div className="eyebrow">{v.niche} · {v.contentType}</div><h3>{v.title}</h3><p>{v.description||'Creator video submitted to Theophos Hub.'}</p>{v.matchScore>0&&<span className="choice selected"><Sparkles size={13}/> Matches your interests</span>}<div className="progressMeta"><Link href={`/creators/${v.creatorId||''}`}><Users size={14}/> {v.creatorName||'Creator'}</Link><Link className="btn soft" href={`/support/${v.id}`}>Discover & support <ArrowUpRight size={14}/></Link></div></article>)}</div>}</section></main>
}
