const creators=[{name:'Ama Finance',niche:'Finance',text:'Simple money lessons for young African creators and entrepreneurs.'},{name:'Faith & Purpose',niche:'Gospel / Christian',text:'Faith, purpose and practical encouragement for everyday life.'},{name:'Tech With Kofi',niche:'Technology',text:'Clear technology tutorials and useful tools for creators.'},{name:'Learn Better',niche:'Education',text:'Study, learning and personal development content.'}];
const $=s=>document.querySelector(s);let firebaseReady=false,auth=null,db=null;
async function initFirebase(){const config=window.THEOPHOS_FIREBASE_CONFIG;if(!config||!config.apiKey||config.apiKey.startsWith('YOUR_'))return false;try{const appMod=await import('https://www.gstatic.com/firebasejs/12.2.1/firebase-app.js');const authMod=await import('https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js');const dbMod=await import('https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js');const app=appMod.initializeApp(config);auth=authMod.getAuth(app);db=dbMod.getFirestore(app);firebaseReady=true;authMod.onAuthStateChanged(auth,user=>{if(user){const name=user.displayName||user.email?.split('@')[0]||'Creator';const greeting=$('#dashGreeting');if(greeting)greeting.textContent=`Welcome, ${name}.`;}});return true}catch(error){console.error('Firebase initialization failed',error);return false}}
function show(route){document.querySelectorAll('.screen').forEach(x=>x.classList.remove('active'));const target=route==='discover'?'discover-app':route;const el=document.getElementById(target)||document.getElementById('home');el.classList.add('active');window.scrollTo({top:0,behavior:'smooth'});history.replaceState(null,'','#'+route);if(route==='discover')renderCreators()}
function message(id,text,success=false){const el=$('#'+id);if(el){el.textContent=text;el.hidden=!text;el.classList.toggle('success',success)}}
function renderCreators(){const q=($('#discoverSearch')?.value||'').toLowerCase();const n=$('#discoverNiche')?.value||'All niches';const list=creators.filter(c=>(n==='All niches'||c.niche===n)&&(!q||`${c.name} ${c.niche} ${c.text}`.toLowerCase().includes(q)));const box=$('#creatorResults');if(!box)return;box.innerHTML=list.length?list.map(c=>`<article class="panel"><div class="eyebrow">${c.niche}</div><h3>${c.name}</h3><p>${c.text}</p><button class="btn soft creatorSupport" data-creator="${c.name}">Discover creator →</button></article>`).join(''):'<article class="panel"><h3>No matching creators yet.</h3><p>Try another niche or search term.</p></article>'}
async function login(){const email=$('#loginEmail')?.value.trim(),pass=$('#loginPassword')?.value;if(!email||!pass){message('loginMessage','Enter your email and password.');return}if(!firebaseReady){message('loginMessage','Firebase is not connected yet. Add the Firebase Web API key in firebase-config.js.');return}try{const m=await import('https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js');await m.signInWithEmailAndPassword(auth,email,pass);message('loginMessage','Signed in successfully.',true);setTimeout(()=>show('dashboard'),300)}catch(e){message('loginMessage',e.code||'Sign-in failed.')}}
async function googleLogin(){if(!firebaseReady){message('loginMessage','Firebase is not connected yet. Add the Firebase Web API key in firebase-config.js.');return}try{const m=await import('https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js');await m.signInWithPopup(auth,new m.GoogleAuthProvider());show('dashboard')}catch(e){message('loginMessage',e.code||'Google sign-in failed.')}}
async function join(){const name=$('#joinName')?.value.trim(),email=$('#joinEmail')?.value.trim(),pass=$('#joinPassword')?.value,niche=$('#joinNiche')?.value;if(!name||!email||pass.length<6||!niche){message('joinMessage','Please enter your name, email, a password of at least 6 characters, and your niche.');return}if(!firebaseReady){message('joinMessage','Firebase is not connected yet. Add the Firebase Web API key in firebase-config.js.');return}try{const am=await import('https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js');const fm=await import('https://www.gstatic.com/firebasejs/12.2.1/firebase-firestore.js');const cred=await am.createUserWithEmailAndPassword(auth,email,pass);await am.updateProfile(cred.user,{displayName:name});await fm.setDoc(fm.doc(db,'users',cred.user.uid),{displayName:name,email,primaryNiche:niche,secondaryNiches:[],goals:[],contentFormat:'both',xp:0,reputation:0,credits:0,streak:0,level:'New Creator',createdAt:fm.serverTimestamp(),updatedAt:fm.serverTimestamp()},{merge:true});const greeting=$('#dashGreeting');if(greeting)greeting.textContent=`Welcome, ${name}.`;show('dashboard')}catch(e){message('joinMessage',e.code||'Account creation failed.')}}
async function logout(){if(firebaseReady&&auth){const m=await import('https://www.gstatic.com/firebasejs/12.2.1/firebase-auth.js');await m.signOut(auth)}show('home')}
async function setup(){await initFirebase();document.addEventListener('click',async e=>{const route=e.target.closest('[data-route]');if(route){e.preventDefault();const r=route.dataset.route;if(r==='home'&&auth?.currentUser)await logout();else show(r)}const support=e.target.closest('.creatorSupport');if(support)message('loginMessage',`${support.dataset.creator} is ready to discover. Sign in to record your support and feedback.`)});window.addEventListener('hashchange',()=>show(location.hash.slice(1)||'home'));show(location.hash.slice(1)||'home');$('#discoverSearch')?.addEventListener('input',renderCreators);$('#discoverNiche')?.addEventListener('change',renderCreators);$('#loginSubmit')?.addEventListener('click',login);$('#googleSubmit')?.addEventListener('click',googleLogin);$('#joinSubmit')?.addEventListener('click',join);$('#submitDemo')?.addEventListener('click',()=>auth?.currentUser?alert('Video submission is the next connected creator feature.'):show('login'))}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',setup);else setup();