import {auth,db,firebaseReady,requireFirebase,signInWithEmailAndPassword,createUserWithEmailAndPassword,doc,setDoc,serverTimestamp} from './firebase.js';
const errorBox=document.querySelector('#authError');
function errorMessage(error){const code=error?.code||'';const map={'auth/invalid-credential':'Email or password is incorrect.','auth/user-not-found':'No account was found with this email.','auth/wrong-password':'Email or password is incorrect.','auth/email-already-in-use':'An account already exists with this email.','auth/weak-password':'Use a stronger password of at least 6 characters.','auth/invalid-email':'Please enter a valid email address.','auth/unauthorized-domain':'This GitHub Pages domain is not authorized in Firebase Authentication.','auth/network-request-failed':'Firebase could not be reached. Check your internet connection.'};if(code.includes('api-key'))return 'Firebase is not configured with a valid Web App API key yet.';return map[code]||`Sign-in failed (${code||'unknown error'}).`}
function show(message){errorBox.textContent=message;errorBox.hidden=false}
function ensure(){try{requireFirebase();return true}catch(e){show(e.message);return false}}
const login=document.querySelector('#loginForm');
if(login)login.addEventListener('submit',async e=>{e.preventDefault();errorBox.hidden=true;if(!ensure())return;const button=login.querySelector('button');button.disabled=true;button.textContent='Signing in…';try{await signInWithEmailAndPassword(auth,document.querySelector('#email').value.trim(),document.querySelector('#password').value);location.href='dashboard.html'}catch(err){show(errorMessage(err))}finally{button.disabled=false;button.textContent='Sign in →'}});
const join=document.querySelector('#joinForm');
if(join)join.addEventListener('submit',async e=>{e.preventDefault();errorBox.hidden=true;if(!ensure())return;const button=join.querySelector('button');button.disabled=true;button.textContent='Creating account…';try{const name=document.querySelector('#name').value.trim(),email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value,niche=document.querySelector('#niche').value;const result=await createUserWithEmailAndPassword(auth,email,password);await setDoc(doc(db,'users',result.user.uid),{displayName:name,email,primaryNiche:niche,secondaryNiches:[],goals:[],youtubeChannelUrl:'',xp:0,reputation:0,credits:0,streak:0,level:'New Creator',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});location.href='dashboard.html'}catch(err){show(errorMessage(err))}finally{button.disabled=false;button.textContent='Create my account →'}});
