import {auth,db,requireFirebase,signInWithEmailAndPassword,createUserWithEmailAndPassword,signInWithPopup,GoogleAuthProvider,doc,getDoc,setDoc,serverTimestamp} from './firebase.js';
const form=document.getElementById('loginForm')||document.getElementById('joinForm');
const googleButton=document.getElementById('googleSignIn');
const errorBox=document.getElementById('authError');
const showError=m=>{if(errorBox){errorBox.textContent=m;errorBox.hidden=false}};
const message=c=>({'auth/invalid-credential':'Email or password is incorrect.','auth/user-not-found':'No account was found with this email.','auth/wrong-password':'Email or password is incorrect.','auth/email-already-in-use':'An account already exists with this email. Try signing in instead.','auth/weak-password':'Please use a stronger password.','auth/invalid-email':'Please enter a valid email address.','auth/unauthorized-domain':'This website domain is not authorized in Firebase Authentication.','auth/operation-not-allowed':'This sign-in method is not enabled in Firebase.','auth/popup-blocked':'Your browser blocked the Google sign-in window. Allow pop-ups and try again.','auth/popup-closed-by-user':'Google sign-in was cancelled.','auth/api-key-not-valid':'The Firebase API key configured for this site is invalid.','auth/invalid-api-key':'The Firebase API key configured for this site is invalid.','auth/network-request-failed':'Firebase could not be reached. Check your connection and try again.'}[c]||`Firebase request failed (${c||'unknown-error'}).`);
async function saveProfile(user){const name=document.getElementById('name')?.value.trim()||user.displayName||user.email?.split('@')[0]||'Creator';const niche=document.getElementById('niche')?.value||'';await setDoc(doc(db,'users',user.uid),{displayName:name,email:user.email||'',primaryNiche:niche,secondaryNiches:[],goals:[],contentFormat:'both',youtubeChannelUrl:'',xp:0,reputation:0,credits:0,streak:0,level:'New Creator',createdAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});}
async function googleSignIn(){requireFirebase();const result=await signInWithPopup(auth,new GoogleAuthProvider());const profile=await getDoc(doc(db,'users',result.user.uid));if(!profile.exists())await saveProfile(result.user);location.href=profile.exists()?'dashboard.html':'join.html';}
if(googleButton){googleButton.addEventListener('click',async()=>{googleButton.disabled=true;if(errorBox)errorBox.hidden=true;try{await googleSignIn();}catch(err){console.error(err);showError(message(err?.code)||err?.message||'Google sign-in failed.')}finally{googleButton.disabled=false;}});}
if(form){form.addEventListener('submit',async e=>{e.preventDefault();if(errorBox)errorBox.hidden=true;const button=form.querySelector('button[type="submit"]');if(button)button.disabled=true;try{requireFirebase();if(form.id==='loginForm'){const r=await signInWithEmailAndPassword(auth,document.getElementById('email').value.trim(),document.getElementById('password').value);const profile=await getDoc(doc(db,'users',r.user.uid));location.href=profile.exists()?'dashboard.html':'join.html';}else{const r=await createUserWithEmailAndPassword(auth,document.getElementById('email').value.trim(),document.getElementById('password').value);await saveProfile(r.user);location.href='dashboard.html';}}catch(err){console.error(err);showError(message(err?.code)||err?.message||'Something went wrong.')}finally{if(button)button.disabled=false;}});}
