'use client'
import Link from 'next/link'
import { useParams, useRouter } from 'next/navigation'
import { useEffect, useState } from 'react'
import { ArrowLeft, Loader2, Send, Users } from 'lucide-react'
import { auth, db, onAuthStateChanged } from '../../../lib/auth'
import { collection, getDocs, limit, orderBy, query, where } from 'firebase/firestore'

export default function CirclePage(){
 const {id}=useParams<{id:string}>();const router=useRouter();const [token,setToken]=useState('');const [circle,setCircle]=useState<any>(null);const [posts,setPosts]=useState<any[]>([]);const [text,setText]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [error,setError]=useState('')
 async function load(t:string){try{const r=await fetch('/api/circles',{headers:{Authorization:`Bearer ${t}`}});const d=await r.json();const found=(d.circles||[]).find((c:any)=>c.id===id);if(!found)throw new Error('Circle not found.');setCircle(found);const snap=await getDocs(query(collection(db,'circlePosts'),where('circleId','==',id),orderBy('createdAt','desc'),limit(40)));setPosts(snap.docs.map(d=>({id:d.id,...d.data()})))}catch(e:any){setError(e.message||'Could not load this circle.')}finally{setLoading(false)}}
 useEffect(()=>onAuthStateChanged(auth,async u=>{if(!u){router.replace('/login');return}const t=await u.getIdToken();setToken(t);load(t)}),[id,router])
 async function post(e:React.FormEvent){e.preventDefault();if(!text.trim())return;setSaving(true);setError('');try{const r=await fetch('/api/circles/post',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({circleId:id,text})});const d=await r.json();if(!r.ok)throw new Error(d.error);setText('');await load(token)}catch(e:any){setError(e.message||'Could not publish post.')}finally{setSaving(false)}}
 if(loading)return <main className="authPage"><div className="authCard"><Loader2 className="spin"/><p>Loading circle...</p></div></main>
 return <main className="appShell"><aside><Link className="brand sideBrand" href="/">theophos<span>hub</span></Link><div className="sideNav"><Link className="sideLink" href="/dashboard">Overview</Link><Link className="sideLink active" href="/circles"><Users size={17}/> Circles</Link><Link className="sideLink" href="/challenges">Challenges</Link><Link className="sideLink" href="/activity">Activity</Link><Link className="sideLink" href="/coach">AI Coach</Link></div></aside><section className="dash"><header className="dashHead"><div><Link href="/circles" className="back"><ArrowLeft size={16}/> Circles</Link><span className="eyebrow">{circle?.niche}</span><h1>{circle?.name}</h1><p>{circle?.description}</p><div className="progressMeta"><span><Users size={14}/> {circle?.memberCount} members</span></div></div></header>{error&&<div className="formError">{error}</div>}{circle?.joined?<form className="panel" onSubmit={post}><div className="panelHead"><div><h3>Start a conversation</h3><p>Share a useful idea, question, lesson or creator update.</p></div></div><textarea value={text} onChange={e=>setText(e.target.value)} maxLength={1000} rows={4} placeholder="What are you learning or working on?"/><button className="btn primary" disabled={saving}>{saving?<><Loader2 className="spin" size={16}/> Posting...</>:<><Send size={16}/> Post to circle</>}</button></form>:<div className="panel"><b>Join this circle to participate.</b><p>Go back to Circles and join the community first.</p><Link href="/circles" className="btn primary">Join circle</Link></div>}<section className="panel" style={{marginTop:18}}><div className="panelHead"><div><h3>Circle conversation</h3><p>Recent posts from members.</p></div></div>{posts.length?posts.map(p=><article key={p.id} className="historyItem" style={{display:'block',marginBottom:10}}><b>{p.authorName||'Creator'}</b><p>{p.text}</p></article>):<div className="emptyState"><Users size={24}/><b>No posts yet.</b><p>Start the first useful conversation in this circle.</p></div>}</section></section></main>
}
