'use client'

import Link from 'next/link'
import { ArrowLeft, ExternalLink, Users, Video, Award } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { collection, doc, getDoc, getDocs, limit, query, where, addDoc, deleteDoc, serverTimestamp } from 'firebase/firestore'
import { auth, db, onAuthStateChanged } from '../../../lib/auth'

export default function CreatorProfilePage(){
 const {id}=useParams<{id:string}>(); const router=useRouter()
 const [profile,setProfile]=useState<any>(null); const [videos,setVideos]=useState<any[]>([]); const [uid,setUid]=useState(''); const [following,setFollowing]=useState(false); const [loading,setLoading]=useState(true); const [busy,setBusy]=useState(false)
 useEffect(()=>{const unsub=onAuthStateChanged(auth,async u=>{if(!u){router.replace('/login');return}setUid(u.uid);try{const p=await getDoc(doc(db,'users',id));if(p.exists())setProfile({id:p.id,...p.data()});const snap=await getDocs(query(collection(db,'videos'),where('creatorId','==',id),limit(12)));setVideos(snap.docs.map(d=>({id:d.id,...d.data()})));const f=await getDocs(query(collection(db,'follows'),where('followerId','==',u.uid),where('followingId','==',id),limit(1)));setFollowing(!f.empty)}finally{setLoading(false)}});return()=>unsub()},[id,router])
 async function toggleFollow(){if(!uid||uid===id)return;setBusy(true);try{const snap=await getDocs(query(collection(db,'follows'),where('followerId','==',uid),where('followingId','==',id),limit(1)));if(!snap.empty){await deleteDoc(snap.docs[0].ref);setFollowing(false)}else{await addDoc(collection(db,'follows'),{followerId:uid,followingId:id,createdAt:serverTimestamp()});setFollowing(true)}}finally{setBusy(false)}}
 if(loading)return <main className="authPage"><div className="authCard">Loading creator...</div></main>
 if(!profile)return <main className="authPage"><div className="authCard"><h1>Creator not found</h1><Link href="/discover" className="btn primary">Back to discover</Link></div></main>
 return <main className="appShell"><aside><Link className="brand sideBrand" href="/">theophos<span>hub</span></Link><div className="sideNav"><Link className="sideLink" href="/dashboard">Overview</Link><Link className="sideLink" href="/discover">Discover</Link><Link className="sideLink" href="/submit"><Video size={17}/> Submit video</Link></div><div className="sideBottom"><Link href="/dashboard">Dashboard</Link></div></aside><section className="dash"><header className="dashHead"><div><Link href="/discover" className="back"><ArrowLeft size={16}/> Discover</Link><div className="eyebrow">CREATOR PROFILE</div><h1>{profile.displayName}</h1><p>{profile.bio||'A creator building in public with the Theophos community.'}</p></div><div className="headActions">{profile.youtubeChannelUrl&&<a className="btn soft" href={profile.youtubeChannelUrl} target="_blank" rel="noreferrer">YouTube <ExternalLink size={15}/></a>}{uid!==id&&<button className="btn primary" onClick={toggleFollow} disabled={busy}>{following?'Following':'Follow creator'}</button>}</div></header><div className="stats"><div><span>LEVEL</span><b>{profile.level||'New Creator'}</b><small>Creator journey</small></div><div><span>XP</span><b>{Number(profile.xp||0).toLocaleString()}</b><small>Community participation</small></div><div><span>REPUTATION</span><b>{Number(profile.reputation||0)}</b><small>Community trust</small></div><div><span>STREAK</span><b>{Number(profile.streak||0)} days</b><small>Keep showing up</small></div></div><div className="panel" style={{marginBottom:20}}><div className="panelHead"><div><h3><Award size={18}/> {profile.primaryNiche||'Creator'} creator</h3><p>{profile.country||'Community creator'} · {profile.contentFormat||'both'}</p></div><span className="choice selected"><Users size={14}/> Community profile</span></div></div><section className="dashGrid">{videos.length?videos.map(v=><article className="panel" key={v.id}><div className="eyebrow">{v.niche} · {v.contentType}</div><h3>{v.title}</h3><p>{v.description||'Video submitted to Theophos Hub.'}</p><div className="progressMeta"><span>Discoverable content</span><Link className="btn soft" href={`/support/${v.id}`}>Support & feedback</Link></div></article>):<div className="panel emptyState"><Video size={26}/><b>No public videos yet.</b><p>This creator has not submitted a video to the community yet.</p></div>}</section></section></main>
}
