'use client'

import Link from 'next/link'
import { ArrowLeft, ArrowRight, Loader2, Video } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { addDoc, collection, serverTimestamp } from 'firebase/firestore'
import { auth, db, onAuthStateChanged, getCurrentCreator } from '../../lib/auth'

const niches=['Finance','Gospel / Christian','Gaming','Technology','Education','Business','Motivation','Lifestyle','Fitness','Beauty','Comedy','African Creators','Other']

export default function Submit(){
 const router=useRouter();const [userId,setUserId]=useState('');const [profile,setProfile]=useState<any>(null);const [youtubeUrl,setYoutubeUrl]=useState('');const [title,setTitle]=useState('');const [description,setDescription]=useState('');const [niche,setNiche]=useState('');const [contentType,setContentType]=useState<'long-form'|'short'>('long-form');const [audience,setAudience]=useState('');const [goal,setGoal]=useState('');const [loading,setLoading]=useState(false);const [error,setError]=useState('')
 useEffect(()=>onAuthStateChanged(auth,async u=>{if(!u){router.replace('/login');return}setUserId(u.uid);setProfile(await getCurrentCreator(u.uid))}),[router])
 function validYoutube(url:string){try{const u=new URL(url);return ['youtube.com','www.youtube.com','m.youtube.com','youtu.be'].includes(u.hostname)}catch{return false}}
 async function submit(e:React.FormEvent){e.preventDefault();setError('');if(!validYoutube(youtubeUrl)){setError('Enter a valid YouTube video URL.');return}if(!title.trim()||!niche){setError('Add a video title and choose a niche.');return}setLoading(true);try{await addDoc(collection(db,'videos'),{creatorId:userId,creatorName:profile?.displayName||'Creator',youtubeUrl:youtubeUrl.trim(),title:title.trim(),description:description.trim(),niche,contentType,targetAudience:audience.trim(),campaignGoal:goal.trim(),status:'active',createdAt:serverTimestamp()});router.push('/discover')}catch{setError('We could not submit this video. Please check your Firebase configuration and try again.')}finally{setLoading(false)}}
 return <main className="onboard"><header className="onboardNav container"><Link className="brand" href="/">theophos<span>hub</span></Link><Link href="/dashboard" className="back"><ArrowLeft size={16}/> Dashboard</Link></header><div className="onboardWrap"><section className="onboardCard"><div className="eyebrow"><Video size={14}/> NEW VIDEO</div><h1>Put your content in front of relevant creators.</h1><p>Theophos does not manufacture views or subscribers. Your video becomes discoverable to real creators who choose how they engage.</p><form onSubmit={submit}><label>YouTube video URL<input required value={youtubeUrl} onChange={e=>setYoutubeUrl(e.target.value)} placeholder="https://youtube.com/watch?v=..."/></label><label>Video title<input required value={title} onChange={e=>setTitle(e.target.value)} placeholder="What is this video about?"/></label><label>Description <small>optional</small><textarea value={description} onChange={e=>setDescription(e.target.value)} placeholder="Give creators enough context to understand the video." rows={4}/></label><label>Niche<select value={niche} onChange={e=>setNiche(e.target.value)}><option value="">Choose a niche</option>{niches.map(n=><option key={n}>{n}</option>)}</select></label><label>Content type<select value={contentType} onChange={e=>setContentType(e.target.value as any)}><option value="long-form">Long-form</option><option value="short">Short</option></select></label><label>Target audience <small>optional</small><input value={audience} onChange={e=>setAudience(e.target.value)} placeholder="e.g. young entrepreneurs in Africa"/></label><label>What feedback do you want? <small>optional</small><input value={goal} onChange={e=>setGoal(e.target.value)} placeholder="e.g. title, hook and retention ideas"/></label>{error&&<div className="formError">{error}</div>}<button className="btn primary large" disabled={loading}>{loading?<><Loader2 size={17} className="spin"/> Submitting...</>:<>Submit video <ArrowRight size={17}/></>}</button></form></section></div></main>
}