'use client'
import Link from 'next/link'
import { useState } from 'react'
import { ArrowRight, Check, ChevronLeft } from 'lucide-react'

const niches=['Finance','Gospel / Christian','Gaming','Technology','Education','Business','Motivation','Lifestyle','Fitness','Beauty','Comedy','African Creators','Other']
const goals=['Get discovered','Improve my content','Get meaningful feedback','Build creator relationships','Grow an audience','Find collaborators','Improve thumbnails','Improve titles & hooks']

export default function Join(){const [step,setStep]=useState(1);const [niche,setNiche]=useState('');const [goals,setGoals]=useState<string[]>([]);const [name,setName]=useState('');const [channel,setChannel]=useState('');
const toggle=(x:string)=>setGoals(g=>g.includes(x)?g.filter(i=>i!==x):[...g,x]);
return <main className="onboard"><header className="onboardNav container"><Link className="brand" href="/">theophos<span>hub</span></Link><span>Step {step} of 3</span></header><div className="onboardWrap"><div className="steps"><span className={step>=1?'active':''}>1</span><i/><span className={step>=2?'active':''}>2</span><i/><span className={step>=3?'active':''}>3</span></div>{step===1&&<section className="onboardCard"><div className="eyebrow">WELCOME, CREATOR</div><h1>Let's build your creator profile.</h1><p>Tell us a little about yourself so Theophos can connect you with relevant creators.</p><label>Display name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Elijah Creates"/></label><label>YouTube channel URL <small>optional for now</small><input value={channel} onChange={e=>setChannel(e.target.value)} placeholder="https://youtube.com/@yourchannel"/></label><button className="btn primary large" onClick={()=>setStep(2)}>Continue <ArrowRight size={17}/></button></section>}{step===2&&<section className="onboardCard"><button className="back" onClick={()=>setStep(1)}><ChevronLeft size={16}/> Back</button><div className="eyebrow">YOUR NICHE</div><h1>What do you create?</h1><p>Choose the niche that best describes your main content.</p><div className="choiceGrid">{niches.map(x=><button className={niche===x?'choice selected':'choice'} onClick={()=>setNiche(x)} key={x}>{niche===x&&<Check size={14}/>} {x}</button>)}</div><button className="btn primary large" disabled={!niche} onClick={()=>setStep(3)}>Continue <ArrowRight size={17}/></button></section>}{step===3&&<section className="onboardCard"><button className="back" onClick={()=>setStep(2)}><ChevronLeft size={16}/> Back</button><div className="eyebrow">YOUR GOALS</div><h1>What do you want help with?</h1><p>Select everything that matters to you. You can change this later.</p><div className="choiceGrid">{goals.map(x=><button className={goals.includes(x)?'choice selected':'choice'} onClick={()=>toggle(x)} key={x}>{goals.includes(x)&&<Check size={14}/>} {x}</button>)}</div><Link href="/dashboard" className="btn primary large">Enter Theophos Hub <ArrowRight size={17}/></Link></section>}</div></main>}
