'use client'

import Link from 'next/link'
import { ArrowLeft, CheckCircle2, ExternalLink, Loader2, Send } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useParams, useRouter } from 'next/navigation'
import { addDoc, collection, doc, getDoc, serverTimestamp } from 'firebase/firestore'
import { auth, db, onAuthStateChanged } from '../../../lib/auth'

const fields=[['hook','Hook'],['title','Title'],['thumbnail','Thumbnail'],['value','Value'],['presentation','Presentation'],['cta','Call to action'],['overall','Overall']]

export default function Support(){
 const {id}=useParams<{id:string}>();const router=useRouter();const [video,setVideo]=useState<any>(null);const [uid,setUid]=useState('');const [missionId,setMissionId]=useState('');const [ratings,setRatings]=useState<Record<string,number>>({});const [note,setNote]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [done,setDone]=useState(false);const [error,setError]=useState('')
 useEffect(()=>{const unsub=onAuthStateChanged(auth,async u=>{if(!u){router.replace('/login');return}setUid(u.uid);try{const snap=await getDoc(doc(db,'videos',id));if(!snap.exists()){setError('This video could not be found.');return}const nextVideo={id:snap.id,...snap.data()};setVideo(nextVideo);const token=await u.getIdToken();const missionResponse=await fetch('/api/missions/start',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({videoId:id})});if(missionResponse.ok){const mission=await missionResponse.json();setMissionId(mission.id)}else if(nextVideo.creatorId===u.uid){setError('You cannot support your own video.')}}catch{setError('Could not load this support mission.')}finally{setLoading(false)}});return()=>unsub()},[id,router])
 async function submit(){setError('');if(Object.keys(ratings).length<7){setError('Please rate each area so your feedback is useful.');return}if(!missionId){setError('This mission is not ready yet. Please refresh and try again.');return}setSaving(true);try{await addDoc(collection(db,'feedback'),{videoId:id,fromCreatorId:uid,...ratings,note:note.trim(),createdAt:serverTimestamp()});const user=auth.currentUser;if(!user)throw new Error('AUTH');const token=await user.getIdToken();const rewardResponse=await fetch('/api/missions/complete',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({missionId})});if(!rewardResponse.ok)throw new Error('REWARD');setDone(true)}catch{setError('Your feedback may have been saved, but the mission reward could not be confirmed. Please do not submit duplicate feedback. Refresh and retry the mission if needed.')}finally{setSaving(false)}}
 if(loading)return <main className="authPage"><div className="authCard"><p>Loading support mission...</p></div></main>
 if(error&&!video)return <main className="authPage"><div className="authCard"><p>{error}</p><Link href="/discover" className="btn primary">Back to discover</Link></div></main>
 return <main className="onboard"><header className="onboardNav container"><Link className="brand" href="/">theophos<span>hub</span></Link><Link href="/discover" className="back"><ArrowLeft size={16}/> Discover</Link></header><div className="onboardWrap"><section className="onboardCard"><div className="eyebrow">CREATOR SUPPORT MISSION · +25 XP</div><h1>{video.title}</h1><p>By {video.creatorName||'Creator'} · {video.niche}</p><a className="btn soft" href={video.youtubeUrl} target="_blank" rel="noreferrer">Open video on YouTube <ExternalLink size={15}/></a>{done?<div className="emptyState"><CheckCircle2 size={34}/><h3>Mission complete.</h3><p>Feedback sent. You earned 25 XP and reputation for genuine community participation.</p><Link href="/discover" className="btn primary">Continue discovering</Link></div>:<><div className="feedbackList">{fields.map(([key,label])=><label key={key}>{label}<select value={ratings[key]||''} onChange={e=>setRatings(r=>({...r,[key]:Number(e.target.value)}))}><option value="">Rate 1–5</option>{[1,2,3,4,5].map(n=><option value={n} key={n}>{n} / 5</option>)}</select></label>)}</div><label>Useful feedback note<textarea value={note} onChange={e=>setNote(e.target.value)} rows={5} placeholder="What specifically could make this video clearer, stronger or more useful?"/></label>{error&&<div className="formError">{error}</div>}<button className="btn primary large" onClick={submit} disabled={saving}>{saving?<><Loader2 size={17} className="spin"/> Completing mission...</>:<><Send size={17}/> Send meaningful feedback</>}</button></>}</section></div></main>
}
