import { auth, db, firebaseConfigured } from './firebase.js'
import { createUserWithEmailAndPassword, signInWithEmailAndPassword, sendPasswordResetEmail } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-auth.js'
import { doc, setDoc, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.1.0/firebase-firestore.js'

const $=id=>document.getElementById(id)
function message(text,error=true){const el=$('message');if(!el)return;el.hidden=false;el.textContent=text;el.className=error?'message error':'message success'}
function requireFirebase(){if(firebaseConfigured)return true;message('Firebase is not configured in this GitHub Pages build yet. Add the Web App configuration to web/js/firebase.js before using accounts.');return false}
function friendly(code){const m={'auth/invalid-credential':'Email or password is incorrect.','auth/email-already-in-use':'An account already exists with this email.','auth/weak-password':'Please use a stronger password.','auth/invalid-email':'Please enter a valid email address.','auth/network-request-failed':'Network connection failed. Try again.','auth/unauthorized-domain':'This GitHub Pages domain is not authorized in Firebase Authentication.','auth/operation-not-allowed':'This sign-in method is not enabled in Firebase.'};return m[code]||`Authentication failed (${code||'unknown-error'}).`}

$('loginBtn')?.addEventListener('click',async()=>{if(!requireFirebase())return;const email=$('email').value.trim(),password=$('password').value; if(!email||!password){message('Enter your email and password.');return}const btn=$('loginBtn');btn.disabled=true;btn.textContent='Signing in...';try{await signInWithEmailAndPassword(auth,email,password);location.href='dashboard.html'}catch(e){message(friendly(e.code))}finally{btn.disabled=false;btn.textContent='Sign in →'}})
$('forgotBtn')?.addEventListener('click',async()=>{if(!requireFirebase())return;const email=$('email').value.trim();if(!email){message('Enter your email first.');return}try{await sendPasswordResetEmail(auth,email);message('Password reset email sent. Check your inbox.',false)}catch(e){message(friendly(e.code))}})
$('joinBtn')?.addEventListener('click',async()=>{if(!requireFirebase())return;const name=$('name').value.trim(),email=$('email').value.trim(),password=$('password').value,channel=$('channel').value.trim(),niche=$('niche').value;if(!name||!email||password.length<6||!niche){message('Please complete your name, email, password and primary niche.');return}const btn=$('joinBtn');btn.disabled=true;btn.textContent='Creating your account...';try{const result=await createUserWithEmailAndPassword(auth,email,password);await setDoc(doc(db,'users',result.user.uid),{displayName:name,email,youtubeChannelUrl:channel,primaryNiche:niche,xp:0,reputation:0,streak:0,level:'New Creator',createdAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});location.href='dashboard.html'}catch(e){message(friendly(e.code))}finally{btn.disabled=false;btn.textContent='Create creator account →'}})
