'use client'

import Link from 'next/link'
import { ArrowLeft, ArrowUpRight, ExternalLink, Sparkles, Video, Plus, Clock } from 'lucide-react'
import { useEffect, useState } from 'react'
import { useRouter } from 'next/navigation'
import { collection, getDocs, limit, query, where } from 'firebase/firestore'
import { auth, db, onAuthStateChanged } from '../../lib/auth'

export default function ContentPage(){
 const router=useRouter(); const [videos,setVideos]=useState<any[]>([]); const [loading,setLoading]=useState(true); const [error,setError]=useState('')
 useEffect(()=>{const unsub=onAuthStateChanged(auth,async u=>{if(!u){router.replace('/login');return}try{const snap=await getDocs(query(collection(db,'videos'),where('creatorId','==',u.uid),limit(50)));const rows=snap.docs.map(d=>({id:d.id,...d.data()}));rows.sort((a,b)=>((b.createdAt?.seconds||0)-(a.createdAt?.seconds||0)));setVideos(rows)}catch{setError('Could not load your content.')}finally{setLoading(false)}});return()=>unsub()},[router])
 if(loading)return <main className="authPage"><div className="authCard"><p>Loading your content...</p></div></main>
 return <main className="appShell"><aside><Link className="brand sideBrand" href="/">theophos<span>hub</span></Link><div className="sideNav"><Link className="sideLink" href="/dashboard">Overview</Link><Link className="sideLink" href="/discover">Discover</Link><Link className="sideLink active" href="/content"><Video size={17}/> My content</Link><Link className="sideLink" href="/coach"><Sparkles size={17}/> AI Coach</Link></div><div className="sideBottom"><Link href="/submit">Submit new video</Link></div></aside><section className="dash"><header className="dashHead"><div><Link href="/dashboard" className="back"><ArrowLeft size={16}/> Dashboard</Link><span className="eyebrow">MY CONTENT</span><h1>Your creator library.</h1><p>Manage submitted videos, open them on YouTube, and send ideas to your AI Coach.</p></div><Link href="/submit" className="btn primary"><Plus size={16}/> Submit video</Link></header>{error&&<div className="formError">{error}</div>}{videos.length?<section className="dashGrid">{videos.map(v=><article className="panel" key={v.id}><div className="panelHead"><div><span className="eyebrow">{v.niche} · {v.contentType}</span><h3>{v.title}</h3></div><span className="choice selected">{v.status||'active'}</span></div><p>{v.description||'No description added.'}</p><div className="progressMeta"><span><Clock size={14}/> {v.createdAt?.seconds?new Date(v.createdAt.seconds*1000).toLocaleDateString():'Recently submitted'}</span><span>{v.targetAudience||'Community discovery'}</span></div><div className="headActions" style={{marginTop:16}}><Link href={`/coach?title=${encodeURIComponent(v.title)}&description=${encodeURIComponent(v.description||'')}&niche=${encodeURIComponent(v.niche||'')}&contentType=${encodeURIComponent(v.contentType||'')}`} className="btn soft"><Sparkles size={15}/> Coach this</Link><Link href={`/support/${v.id}`} className="btn soft">Feedback <ArrowUpRight size={15}/></Link><a href={v.youtubeUrl} target="_blank" rel="noreferrer" className="btn soft">YouTube <ExternalLink size={15}/></a></div></article>)}</section>:<div className="panel emptyState"><Video size={30}/><b>Your content library is empty.</b><p>Submit your first YouTube video and make it discoverable to relevant creators.</p><Link href="/submit" className="btn primary">Submit your first video</Link></div>}</section></main>
}
