'use client'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { Trophy, ArrowLeft, Loader2, CheckCircle2, Target } from 'lucide-react'
import { auth, onAuthStateChanged } from '../../lib/auth'
import { fetchApi } from '../../lib/api-client'
export default function ChallengesPage(){
 const [token,setToken]=useState('');const [items,setItems]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState('');const [error,setError]=useState('')
 useEffect(()=>onAuthStateChanged(auth,async u=>{if(!u){location.href='/login';return}const t=await u.getIdToken();setToken(t);load(t)}),[])
 async function load(t=token){if(!t)return;setLoading(true);setError('');try{const d=await fetchApi<{challenges:any[]}>('/api/challenges',{headers:{Authorization:`Bearer ${t}`}});setItems(d.challenges||[])}catch(e:any){setError(e.message||'Could not load challenges.')}finally{setLoading(false)}}
 async function act(id:string,action:'join'|'complete'){setBusy(id+action);setError('');try{await fetchApi('/api/challenges',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({challengeId:id,action})});await load()}catch(e:any){setError(e.message||'Challenge update failed.')}finally{setBusy('')}}
 return <main className="appShell"><aside><Link className="brand sideBrand" href="/">theophos<span>hub</span></Link><div className="sideNav"><Link className="sideLink" href="/dashboard">Overview</Link><Link className="sideLink" href="/discover">Discover</Link><Link className="sideLink" href="/circles">Creator Circles</Link><Link className="sideLink active" href="/challenges"><Trophy size={17}/> Challenges</Link><Link className="sideLink" href="/activity">Activity</Link><Link className="sideLink" href="/coach">AI Coach</Link></div></aside><section className="dash"><header className="dashHead"><div><Link href="/dashboard" className="back"><ArrowLeft size={16}/> Dashboard</Link><span className="eyebrow">CREATOR CHALLENGES</span><h1>Build by doing.</h1><p>Small, real actions that help you publish, support creators and build your network.</p></div></header>{error&&<div className="formError">{error}</div>}{loading?<Loader2 className="spin"/>:<div className="dashGrid">{items.map(c=>{const p=c.participant;const completed=p?.status==='completed';const joined=p?.status==='active';return <article className="panel" key={c.id}><div className="progressMeta"><span className="eyebrow"><Target size={13}/> CHALLENGE</span><b>+{c.xp} XP</b></div><h3>{c.title}</h3><p>{c.description}</p><div className="mission" style={{marginTop:18}}><div><span className="tag">REAL PROGRESS</span><h3>{completed?c.requirement:0} / {c.requirement}</h3><p>Verified actions completed</p></div><div className="progress">{completed?'✓':joined?'•':'→'}</div></div><div className="progressMeta">{completed?<span><CheckCircle2 size={15}/> Completed</span>:!joined?<button className="btn primary" disabled={busy===c.id+'join'} onClick={()=>act(c.id,'join')}>{busy===c.id+'join'?<Loader2 className="spin" size={15}/>:<>Join challenge</>}</button>:<button className="btn soft" disabled={busy===c.id+'complete'} onClick={()=>act(c.id,'complete')}>{busy===c.id+'complete'?<Loader2 className="spin" size={15}/>:<>Check my progress</>}</button>}</div></article>})}</div>}</section></main>
}
