'use client'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { Users, Plus, ArrowLeft, Loader2, Search } from 'lucide-react'
import { auth, onAuthStateChanged } from '../../lib/auth'
import { fetchApi } from '../../lib/api-client'

const niches=['Finance','Gospel / Christian','Gaming','Technology','Education','Business','Motivation','Lifestyle','Fitness','Beauty','Comedy','African Creators','Other']
export default function CirclesPage(){
 const [token,setToken]=useState(''); const [circles,setCircles]=useState<any[]>([]); const [search,setSearch]=useState(''); const [showCreate,setShowCreate]=useState(false); const [name,setName]=useState(''); const [niche,setNiche]=useState(''); const [description,setDescription]=useState(''); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [error,setError]=useState('')
 useEffect(()=>onAuthStateChanged(auth,async u=>{if(!u){location.href='/login';return}const t=await u.getIdToken();setToken(t);load(t)}),[])
 async function load(t=token){if(!t)return;setLoading(true);setError('');try{const d=await fetchApi<{circles:any[]}>('/api/circles',{headers:{Authorization:`Bearer ${t}`}});setCircles(d.circles||[])}catch(e:any){setError(e.message||'Could not load circles.')}finally{setLoading(false)}}
 async function toggle(c:any){setError('');try{const d=await fetchApi<{joined:boolean;memberCount:number}>('/api/circles/join',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({circleId:c.id,action:c.joined?'leave':'join'})});setCircles(x=>x.map(a=>a.id===c.id?{...a,joined:d.joined,memberCount:d.memberCount}:a))}catch(e:any){setError(e.message||'Could not update membership.')}}
 async function create(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{await fetchApi('/api/circles',{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({name,niche,description})});setName('');setNiche('');setDescription('');setShowCreate(false);await load()}catch(e:any){setError(e.message||'Could not create circle.')}finally{setSaving(false)}}
 const filtered=circles.filter(c=>`${c.name} ${c.niche} ${c.description}`.toLowerCase().includes(search.toLowerCase()))
 return <main className="appShell"><aside><Link className="brand sideBrand" href="/">theophos<span>hub</span></Link><div className="sideNav"><Link className="sideLink" href="/dashboard">Overview</Link><Link className="sideLink" href="/discover">Discover</Link><Link className="sideLink active" href="/circles"><Users size={17}/> Creator Circles</Link><Link className="sideLink" href="/challenges">Challenges</Link><Link className="sideLink" href="/activity">Activity</Link><Link className="sideLink" href="/coach">AI Coach</Link></div></aside><section className="dash"><header className="dashHead"><div><Link href="/dashboard" className="back"><ArrowLeft size={16}/> Dashboard</Link><span className="eyebrow">CREATOR COMMUNITY</span><h1>Find your people.</h1><p>Join focused creator circles, share what you are learning, and build real relationships around your niche.</p></div><button className="btn primary" onClick={()=>setShowCreate(v=>!v)}><Plus size={16}/> Create circle</button></header>{error&&<div className="formError">{error}</div>}{showCreate&&<form className="panel" onSubmit={create}><div className="panelHead"><div><h3>Start a circle</h3><p>Create a focused space for a niche or creator community.</p></div></div><div className="formGrid"><label>Name<input value={name} onChange={e=>setName(e.target.value)} maxLength={60} required placeholder="e.g. Ghana Finance Creators"/></label><label>Niche<select value={niche} onChange={e=>setNiche(e.target.value)} required><option value="">Choose niche</option>{niches.map(n=><option key={n}>{n}</option>)}</select></label></div><label>Description<textarea value={description} onChange={e=>setDescription(e.target.value)} maxLength={500} placeholder="What is this circle for?"/></label><button className="btn primary" disabled={saving}>{saving?<><Loader2 className="spin" size={16}/> Creating...</>:<>Create circle</>}</button></form>}<div className="panel"><div className="panelHead"><div><h3>Creator circles</h3><p>{circles.length} communities available.</p></div><div className="searchBox"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search circles"/></div></div>{loading?<Loader2 className="spin"/>:filtered.length?<div className="dashGrid">{filtered.map(c=><article className="panel" key={c.id}><span className="eyebrow">{c.niche}</span><h3>{c.name}</h3><p>{c.description||'A focused creator community on Theophos Hub.'}</p><div className="progressMeta"><span><Users size={14}/> {c.memberCount} members</span><div style={{display:'flex',gap:8}}><Link href={`/circles/${c.id}`} className="btn soft">Open</Link><button className="btn soft" onClick={()=>toggle(c)}>{c.joined?'Leave':'Join circle'}</button></div></div></article>)}</div>:<div className="emptyState"><Users size={25}/><b>No matching circles yet.</b><p>Be the first creator to start one.</p></div>}</div></section></main>
}
