'use client'
import Link from 'next/link'
import { useEffect, useState } from 'react'
import { Activity, ArrowLeft, ExternalLink, Loader2, Video } from 'lucide-react'
import { auth, onAuthStateChanged } from '../../lib/auth'
export default function ActivityPage(){
 const [token,setToken]=useState('');const [items,setItems]=useState<any[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('')
 useEffect(()=>onAuthStateChanged(auth,async u=>{if(!u){location.href='/login';return}const t=await u.getIdToken();setToken(t);load(t)}),[])
 async function load(t=token){if(!t)return;setLoading(true);try{const r=await fetch('/api/activity',{headers:{Authorization:`Bearer ${t}`}});const d=await r.json();if(!r.ok)throw new Error(d.error);setItems(d.activities||[])}catch(e:any){setError(e.message||'Could not load activity.')}finally{setLoading(false)}}
 function time(value:any){if(!value)return 'Recently';const diff=Math.max(0,Date.now()-new Date(value).getTime());const m=Math.floor(diff/60000);if(m<1)return 'Just now';if(m<60)return `${m}m ago`;const h=Math.floor(m/60);if(h<24)return `${h}h ago`;return `${Math.floor(h/24)}d ago`}
 return <main className="appShell"><aside><Link className="brand sideBrand" href="/">theophos<span>hub</span></Link><div className="sideNav"><Link className="sideLink" href="/dashboard">Overview</Link><Link className="sideLink" href="/discover">Discover</Link><Link className="sideLink" href="/circles">Creator Circles</Link><Link className="sideLink" href="/challenges">Challenges</Link><Link className="sideLink active" href="/activity"><Activity size={17}/> Activity</Link><Link className="sideLink" href="/coach">AI Coach</Link></div></aside><section className="dash"><header className="dashHead"><div><Link href="/dashboard" className="back"><ArrowLeft size={16}/> Dashboard</Link><span className="eyebrow">YOUR CREATOR NETWORK</span><h1>Stay close to the work.</h1><p>Recent videos from you and creators you follow. Discover first, then choose how you want to support them.</p></div><Link href="/discover" className="btn primary">Discover creators</Link></header>{error&&<div className="formError">{error}</div>}<section className="panel"><div className="panelHead"><div><h3>Recent activity</h3><p>Your feed is based on real creator submissions and follows.</p></div></div>{loading?<Loader2 className="spin"/>:items.length?<div className="activityList">{items.map(v=><article className="activityItem" key={v.id}><div className="submitIcon"><Video size={20}/></div><div><div className="progressMeta"><b>{v.creator?.displayName||v.creatorName||'Creator'}</b><span>{time(v.createdAt)}</span></div><h3>{v.title}</h3><p>{v.niche||'Creator content'} · {v.contentType||'video'}</p><div className="heroActions"><Link className="btn soft" href={`/creators/${v.creatorId}`}>View creator</Link><Link className="btn primary" href={`/support/${v.id}`}>Support mission</Link><a className="btn ghost" href={v.youtubeUrl} target="_blank" rel="noreferrer">Open YouTube <ExternalLink size={14}/></a></div></div></article>)}</div>:<div className="emptyState"><Activity size={25}/><b>Your network feed will grow here.</b><p>Follow creators from Discover, then their new submitted videos can appear here.</p><Link href="/discover" className="btn soft">Find creators</Link></div>}</section></section></main>
}